name: Test & Deploy

on:
    push:
        branches:
            - "master"

jobs:
    unit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm test:unit

    deploy:
        needs: unit

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Deploy
              run: pnpm task:deploy:workflow
              env:
                  GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
