name: Test & Build

on:
    push:
        branches:
            - "**"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    unit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint

            - name: Typecheck
              run: pnpm typecheck

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm test:unit

            - name: Codecov
              uses: codecov/codecov-action@v7
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

    build:
        needs: unit

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm task:release

            - name: Upload .zip
              uses: actions/upload-artifact@v7
              with:
                  name: dist.zip
                  path: releases/dist.zip
